# Generated by Django 3.2.6 on 2021-08-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name1', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='info',
            name='description',
        ),
        migrations.RemoveField(
            model_name='info',
            name='title',
        ),
        migrations.AddField(
            model_name='info',
            name='description_en',
            field=models.TextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='description_ru',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='description_uz',
            field=models.TextField(default=1, verbose_name='Mahsulot haqida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='title_en',
            field=models.CharField(default=1, max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='title_ru',
            field=models.CharField(default=1, max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='title_uz',
            field=models.CharField(default=1, max_length=100, verbose_name='Nomi'),
            preserve_default=False,
        ),
    ]
