# Generated by Django 3.2 on 2021-07-14 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210714_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='botuser',
            name='referal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referals', to='backend.botuser'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='lang',
            field=models.CharField(choices=[('uz', 'Uz'), ('ru', 'Ru'), ('en', 'En')], default='uz', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uz',
            field=models.TextField(verbose_name='Mahsulot haqida'),
        ),
    ]
