# Generated by Django 3.2.6 on 2021-08-21 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_comment_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.info'),
        ),
        migrations.AlterField(
            model_name='info',
            name='description_uz',
            field=models.TextField(verbose_name='haqida'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.botuser')),
            ],
        ),
    ]
