# Generated by Django 3.2.6 on 2021-08-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210821_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Baxo', 'verbose_name_plural': 'Baxolar'},
        ),
    ]
