# Generated by Django 3.2 on 2021-08-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210822_1249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='ShopInfo',
        ),
    ]
