# Generated by Django 3.2 on 2021-08-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210716_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='type',
            field=models.CharField(default='user', max_length=10),
        ),
    ]
