# Generated by Django 3.2 on 2021-08-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_info_shopinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
