# Generated by Django 3.2 on 2021-08-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210804_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Self call', 'Self Call'), ('Payment delivery', 'Payment Delivery')], default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('In queue', 'In Queue'), ('Processed', 'Processed'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='In queue', max_length=25),
        ),
    ]
