# Generated by Django 3.2 on 2021-08-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210822_1257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopInfo',
            new_name='AboutShop',
        ),
    ]
