# Generated by Django 3.2 on 2021-08-22 08:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_shopinfo_aboutshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutshop',
            name='description_en',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='aboutshop',
            name='description_ru',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='aboutshop',
            name='description_uz',
            field=tinymce.models.HTMLField(verbose_name='haqida'),
        ),
    ]
