# Generated by Django 3.2 on 2021-08-22 08:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210822_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutshop',
            name='location_en',
            field=tinymce.models.HTMLField(default='', verbose_name='Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutshop',
            name='location_ru',
            field=tinymce.models.HTMLField(default='', verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutshop',
            name='location_uz',
            field=tinymce.models.HTMLField(default='', verbose_name='Manzil'),
            preserve_default=False,
        ),
    ]
