# Generated by Django 3.2 on 2021-08-22 08:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210822_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutshop',
            name='location_en',
        ),
        migrations.RemoveField(
            model_name='aboutshop',
            name='location_ru',
        ),
        migrations.RemoveField(
            model_name='aboutshop',
            name='location_uz',
        ),
        migrations.AddField(
            model_name='aboutshop',
            name='location_and_contacts_en',
            field=tinymce.models.HTMLField(default='', verbose_name='Contacts and location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutshop',
            name='location_and_contacts_ru',
            field=tinymce.models.HTMLField(default='', verbose_name='Контакты и адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutshop',
            name='location_and_contacts_uz',
            field=tinymce.models.HTMLField(default=1, verbose_name='Bog`lanish va manzil'),
            preserve_default=False,
        ),
    ]
