# Generated by Django 3.2 on 2021-08-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210822_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutshop',
            old_name='location_and_contacts_en',
            new_name='contacts_and_location_en',
        ),
        migrations.RenameField(
            model_name='aboutshop',
            old_name='location_and_contacts_ru',
            new_name='contacts_and_location_ru',
        ),
        migrations.RenameField(
            model_name='aboutshop',
            old_name='location_and_contacts_uz',
            new_name='contacts_and_location_uz',
        ),
    ]
