# Generated by Django 3.2.6 on 2021-08-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_review_options'),
        ('backend', '0014_auto_20210822_1419'),
    ]

    operations = [
    ]
