# Generated by Django 3.2.6 on 2021-08-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20210824_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cook', models.CharField(max_length=50)),
                ('driver', models.CharField(max_length=50)),
            ],
        ),
    ]
