# Generated by Django 4.0.4 on 2022-08-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_botuser_full_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
