# Generated by Django 4.0.4 on 2022-08-26 05:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Reserved', 'Reserved'), ('In queue', 'In Queue'), ('Processed', 'Processed'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Reserved', max_length=25)),
                ('delivery_type', models.CharField(choices=[('Self call', 'Self Call'), ('Payment delivery', 'Payment Delivery')], max_length=20)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Payme', 'Payme')], max_length=20)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('purchases', models.ManyToManyField(to='backend.purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='backend.botuser')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
            managers=[
                ('orders', django.db.models.manager.Manager()),
            ],
        ),
    ]
