# Generated by Django 4.0.4 on 2022-09-20 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('In queue', 'In Queue'), ('Processed', 'Processed'), ('Preparing', 'Preparing'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Reserved', max_length=25),
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Nomi')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Название')),
                ('title_en', models.CharField(max_length=100, verbose_name='Title')),
                ('price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
            ],
        ),
    ]
