# Generated by Django 4.0.4 on 2022-09-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_order_status_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
